version: '3.9'

services:
  api:
    build: .
    container_name: academia-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/academia
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//

  db:
    image: postgres:15
    container_name: academia-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: academia-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: academia-rabbitmq
    ports:
      - "5672:5672"   # Porta padrão para conexões de apps
      - "15672:15672" # Porta do painel web (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  checkin_worker:
    build: .
    container_name: worker-checkins
    depends_on:
      - redis
      - db
      - rabbitmq
    command: >
      sh -c "sleep 5 && python -m app.workers.checkin_worker"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/academia
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//

  report_worker:
    build: .
    container_name: worker-relatorios
    depends_on:
      - redis
      - db
      - rabbitmq
    command: >
      sh -c "sleep 5 && python -m app.workers.report_worker"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/academia
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//

  churn_updater:
    build: .
    container_name: worker-churn
    depends_on:
      - redis
      - db
      - rabbitmq
    command: >
      sh -c "sleep 5 && python -m app.workers.churn_updater"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/academia
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//

volumes:
  postgres_data:
